config/routes.rb
Rails.application.routes.draw do
  # resources :words
  #TODO: Add Welcome controller with home action and put it as root 'welcome#home'
  root 'users#show'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :users
  get 'define/quotes/:quote_id/:word_query', to: 'quotes#define', as: 'word_definition'
  get '/users/:id/favorites', to: 'users#favorites', as: 'favorite_quotes'
  post '/users/:id/favorites/:quote_id', to: 'users#remove_favorite'
  post '/quotes/:quote_id', to: 'users#add_to_user_favorites'
  get '/quotes', to: 'quotes#index'
  delete 'quotes/:id', to: 'quotes#destroy'

  resources :favorites
  # resources :quotes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/quote.rb
class Quote < ApplicationRecord
    has_many :favorites
    has_many :users, through: :favorites

    def split_quote_array
        split_quote = self.content.split(" ")
        # post action will strip punctuation from word in quote_controller
    end

    def self.normal_word(word)
        word.split(/\W/)[0]
    end

   

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    @@list_of_quotes = Quote.all

   def index
    @user = User.find(current_user.id)
    @quotes = @@list_of_quotes.to_a
   end

   # def show
   # end

   # def query
   #    @quote = Quote.find(params[:quote_id])
   #    @quote.word_query = params[:word_query]
   #  # byebug
   # #  redirect_to word_definition(@quote.id)
   #    redirect_to 'define/quotes/:quote_id/:word_query'
   # end

   def define
      @quote = Quote.find(params[:quote_id])
      @quote.word_query = params[:word_query]
      word = @quote.word_query.split(/\W/).flatten[0]
      api_key = ENV["API_KEY"]
      url = 'https://www.dictionaryapi.com/api/v3/references/collegiate/json/'
      endpoint = url + word + "?key=" + api_key
      @response = RestClient.get(endpoint)
      @quote.word_definition = JSON.parse(@response)

      if !JSON.parse(@response)[0].include?("meta")
         @header_word = "Definition not found."
      elsif JSON.parse(@response)[0].include?("cxs")
         @header_word = JSON.parse(@response)[0]["hwi"]["hw"]
         @cxs_def = JSON.parse(@response)[0]["cxs"].map{|array| array["cxl"]}
      else
         @header_word = JSON.parse(@response)[0]["hwi"]["hw"]
         if !JSON.parse(@response)[0].include?("def")
            @pronunciation = JSON.parse(@response)[0]["hwi"]["prs"][0]["mw"]
         end
         @def = JSON.parse(@response)[0]["def"][0]["sseq"]
      end
      # byebug
   end

end

app/views/quotes/_index_quote.html.erb
<% unless @user.quotes.include?(index_quote) %>
    <div class="transbox">
        <h3>
            "
            <% index_quote.split_quote_array.each do |word| %>
                <% if Quote.normal_word(word) != nil %>
                    <%= link_to word, word_definition_path(:controller => 'quotes', :action => 'define', :method => 'get', :quote_id => index_quote.id, :word_query => Quote.normal_word(word)) %>
                <% else %>
                    <%= word %>
                <% end %>
            <% end %>
            " - <%= index_quote.author %>
        </h3><br><br>
        <%= button_to "Add to Favorites", :controller => 'users', :action => 'add_to_user_favorites', :method => 'post', :quote_id => index_quote.id %>
    </div>
<% end %>

app/views/quotes/define.html.erb
<h1 style="color:lightblue;"><em><%= @header_word %></em></h6>

<% if JSON.parse(@response)[0].include?("def") %>

    <h3><%= @pronunciation %></h3>

    <p><strong>Parts Of Speech: </strong><%= JSON.parse(@response)[0]["fl"] %></p>

    <h4 style="color:lightblue;">Definition:</h4>
    <% @def.each do |var| %>
        <% var.each do |sense| %>
            <p>
                <%= sense[1]["sn"] %>: 
                <%= sense[1]["dt"][0][1] %><br><br>
            </p>
        <% end %>
    <% end %>

<% elsif JSON.parse(@response)[0].include?("cxs") %>
    <h4>Definition:</h4>
    <% @cxs_def.each do |cxl| %>
        <p>
            <%= cxl %>
        </p>
    <% end %>
<% end %>

<%= link_to 'Back to Quotes', quotes_path %>

app/views/quotes/index.html.erb
<%= render partial: "index_quote", collection: @quotes %>